site_name: test-koek
repo_url: https://github.com/joostnjns/test-koek
site_url: https://joostnjns.github.io/test-koek
site_description: De code in deze repo is gebruikt om de coockiecutter en functionaliteiten te testen.
site_author: Joost Neujens
edit_uri: edit/main/docs/
repo_name: joostnjns/test-koek
copyright: Maintained by <a href="https://joostnjns.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joostnjns/test-koek
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/test-koek

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true